pre-commit:
  parallel: true
  jobs:
    - name: lint
      run: bun lint --fix {staged_files}
      glob:
        - "*.{js,ts,jsx,tsx}"
      stage_fixed: true

    - name: format
      run: bun prettier --write {staged_files}
      glob:
        - "*.{js,ts,jsx,tsx,json,css,md}"
      stage_fixed: true

    - name: gitleaks
      run: gitleaks git --pre-commit
