pre-commit:
  parallel: true
  jobs:
    - name: lint
      run: pnpm eslint {staged_files}
      glob:
        - "*.{js,ts,jsx,tsx,json,css,md}"

    - name: format
      run: pnpm prettier --write {staged_files}
      glob:
        - "*.{js,ts,jsx,tsx,json,css,md}"
      stage_fixed: true

    - name: gitleaks
      run: gitleaks detect -v
