services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # env_file:
    #   - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    profiles:
      - app # only start app if I explicitly ask for it
