services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TURSO_AUTH_TOKEN: ${TURSO_AUTH_TOKEN}
        DATABASE_URL: ${DATABASE_URL}
    env_file: .env
    ports:
      - "8000:3000"

