name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

defaults:
  run:
    shell: bash

jobs:
  lint:
    strategy:
      matrix:
        node-version: ['18.*', '20.*']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    name: 'Lint: Node.js ${{ matrix.node-version }} - OS: ${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm nuxi typecheck

      - name: Linting
        run: pnpm biome ci .
