name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

defaults:
  run:
    shell: bash

jobs:
  lint:
    strategy:
      matrix:
        node-version: ['18.*', '20.*']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    name: 'Lint: Node.js ${{ matrix.node-version }} - OS: ${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm nuxi typecheck

      - name: Linting
        run: pnpm biome ci .
